plugins:
  - file: "./target/wasm32-wasip2/debug/front_console_plugin.wasm"
    name: "front:console"
    access:
      - !console_input "prompt>"
      - !console_print 102400
    config:
      subscriptions:
        - "system:info"
        - "system:error"
      targets:
        - "system:info"
    allow_background: true

  - file: "./target/wasm32-wasip2/debug/tool_calculator_plugin.wasm"
    name: "tool:calculator"
    access: []
    config: {}
    allow_background: false

  - file: "./target/wasm32-wasip2/debug/agent_plugin.wasm"
    name: "agent:demo"
    access: []
    config:
      name: "demo"
      model:
        model_name: "gpt-4o-mini"
        api_url: "https://api.openai.com/v1"
        api_key: null
      system_prompt: "You are a helpful assistant."
      tools:
        - "calculator"
    allow_background: false

metrics:
  enabled: false
  host: "127.0.0.1"
  port: 9090
  update_interval_secs: 15
  location: "/metrics"

logger: