[[plugins]]
file = "./target/wasm32-wasip2/debug/front_console_plugin.wasm"
name = "front:console"
access = [
  { console_input = "prompt>" },
  { console_print = 102400 }
]
allow_background = true
[plugins.config]
subscriptions = ["system:info", "system:error"]
targets = ["system:info"]

[metrics]
enabled = false
host = "127.0.0.1"
port = 9090
update_interval_secs = 15
location = "/metrics"
