[package]
name = "tool_calculator_plugin"
version = "0.1.0"
edition = "2024"
description = "Tool calculator"

[lib]
# Важно: cdylib указывает компилятору собрать динамическую C-библиотеку,
# которую затем утилиты WASM превращают в компонент.
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.58"
meval = { git = "https://github.com/UncleAndy/meval-rs" }
