package ai:host;

interface types {
  record event {
    request-id: string, // Сквозной ID пользовательской сессии
    session-id: string, // Сквозной ID пользовательского запроса
    source: string,     // Отправитель (напр., "agent_manager")
    target: string,     // Получатель (напр., "tool:calculator" или "agent:coder")
    topic: string,      // "call"/"response"/"info"/"error"
    payload: string,
  }
}

interface event-bus {
  use types.{event};
  publish-event: func(ev: event);
}

interface console {
  print-line: func(line: string);
  read-line: async func(prompt: string) -> option<string>;
}

interface log {
  debug: func(line: string);
  info: func(line: string);
  warn: func(line: string);
  error: func(line: string);
}

interface plugin-lifecycle {
  use types.{event};

  init: async func(config-json: string) -> list<string>;
  run: async func(); // Если нужен параллельный цикл обработки для плагина.
  handle-event: async func(ev: event);
}

world host-plugin {
  import event-bus;
  import console;
  import log;
  export plugin-lifecycle;
}
